import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Portfolio demo test',
  description: 'Generated by create next app',
}

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-10 h-screen w-screen`}>
        <header className="mb-5">
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  )
}

export default RootLayout
